# Generated by Django 5.1.7 on 2025-07-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_blocked",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
